### ISSUE TITLE
将搜索引擎合并成一个选项。并调整右键菜单中的“搜索“为“查找”

### ISSUE THREAD

**Issue by JavaJoin** [martyr-deepin/deepin-terminal-gtk#27]
现在右键菜单提供了google、百度、bing搜索，很方便，不过三个菜单堆在一起，感觉还是挺长的。所以，提议将三个菜单统一合并成一个一个“在线搜索”或“搜索”选项，默认搜索引擎的设置放置到设置中“默认搜索引擎”中以下拉菜单的方式进行设置，例如外国版本默认使用google、中国区域默认使用百度，或者压根默认是谷歌搜索，但允许用户自我选择其他搜索引擎（如百度、bing之类的，自定义那就更完美了）。
右键菜单的“搜索”个人感觉写为“查找”更合适，而搜索则用于搜索引擎。

**Comment by manateelazycat** [comment]
@JavaJoin 补丁 https://github.com/manateelazycat/deepin-terminal/commit/032475995df094c144320c0a172fee1b38d49076 https://github.com/manateelazycat/deepin-terminal/commit/de67b6af00d3bb1bc3bc7c67f23da260bde5dc03 已经修复了，合并搜索引擎到子菜单了。

自定义搜索引擎的功能我一会做。

**Comment by manateelazycat** [comment]
自定义搜索引擎的功能已经支持，补丁请看：
https://github.com/manateelazycat/deepin-terminal/commit/3b09c026df870e693a89e5d14dc480912b21b899

自定搜索引擎的方法：

Customize search engine
Deepin terminal build-in many search engine for engineer, such as Google, Bing, Baidu, GitHub, Stackover Flow, DuckDuckGo. Anyway, if you want build your own search engine, just follow below command:

Create config file ~/.config/deepin/deepin-terminal/search-engine-config.conf with below content:

[flickr]
name=Flickr
api=https://www.flickr.com/search/?text=%s

[googleimage]
name=Google Image
api=http://images.google.com/search?q=%s


Content in [] is searchengine name, use by terminal for id search.

name mean human name of search engine, you can name it to anything you like

api mean search api for search engine, note, you need use %s replace search keyword, otherwise, deepin-terminal don't know how to concat search api url and search keyboard.
