### ISSUE TITLE
Maximizing terminal

### ISSUE THREAD

**Issue by apit** [martyr-deepin/deepin-terminal-gtk#29]
Deepin Terminal has the ability to split window into panes. But, often times, i want to temporarily maximize active pane  e.g. when viewing log. By temporarily i mean i can later restore it back to previously split-ed
split-ed panes. I don't think i can do this in Deepin Terminal? 

This feature is the only reason i keep [Terminator](https://gnometerminator.blogspot.co.id/p/introduction.html) installed.

**Comment by manateelazycat** [comment]
I will consider this feature, thanks suggesion

**Comment by manateelazycat** [comment]
@apit It's a problem that restore split layout, because deepin-terminal not like tmux or screen, very terminal  splited window is a Qt Widget, it's easy to maximize active pane, but hard to restore pane layout, user may create new pane after maximize.

I think a new idea, you can move acitve pane to new tab once you split some pane in current tab. You can maximize active pane and keep context, you can switch to tab to find other split pane.

How do you think above idea?

**Comment by Fadelis** [comment]
I also would like to see this feature implemented. One of the things that makes me go back to using Tilix/Terminator instead of Deepin Terminal.

**Comment by byaka** [comment]
same for me. this feature needed rarely, but when it coming - it a real problem so my default terminal still Terminator :(

**Comment by byaka** [comment]
> @apit 
> How do you think above idea?

think it not perfect but useful alternative

**Comment by apit** [comment]
@manateelazycat what do you mean by "user may create new pane after maximize"?

Shortcuts for creating new pane should be disabled once we're in max 'mode'.

**Comment by justforlxz** [comment]
Sorry, this issue will be closed soon. If it is necessary to discuss it again, please create a new issue.
