### ISSUE TITLE
Add Quake Shortcut to terminal settings

### ISSUE THREAD

**Issue by Klauswk** [martyr-deepin/deepin-terminal-gtk#57]
I spend some time searching how to change the default `ALT + F2` shortcut in the terminal preferences, and i found they were in the keyboard shortcuts.

Would be great if this been configure in the terminal preferences as well.

**Comment by palxex** [comment]
@Klauswk Have you found how to tweak it in config file or code? Due to lack of vala knowledge  I can not even found them :(

**Comment by Klauswk** [comment]
@palxex , they use a [signal/slot](https://doc.qt.io/qt-5/signalsandslots.html) system, still trying to find the correct file where is persist, but I know this call is made in the following source file:

https://github.com/linuxdeepin/dde-control-center/blob/master/modules/keyboard/shortcutwidget.cpp#L168

**Comment by Tset-Noitamotua** [comment]
In addition to that when Quake terminal is opened via shortcut it should get focus - same as opening it via menu.
Actual behavior is that when you open it vie Alt + F2 the terminal does not have focus.

**Comment by Tset-Noitamotua** [comment]
> In addition to that when Quake terminal is opened via shortcut it should get focus - same as opening it via menu.
> Actual behavior is that when you open it vie Alt + F2 the terminal does not have focus.

Have to correct myself: this seems to happen only if you follow this sequence:
1) open Quake with Alt + F2
2) close Quake with Alt + F2
3) open Quake again with Alt + F2     /  now it has  no focus

**Comment by BLumia** [comment]
> Would be great if this been configure in the terminal preferences as well.

Deepin-terminal didn't have a daemon process to listen user shortcuts when deepin-terminal is not running, so only the desktop environment can do this job. It seems there are not yet a standard for register shortcuts so maybe we can't do this now, since there are also people using deepin-terminal with other DE.

> Actual behavior is that when you open it vie Alt + F2 the terminal does not have focus.

It seems this issue is not related to this topic, so please consider open another issue for your issue :)

btw I remember I did fixed this issue in earlier release (in https://github.com/linuxdeepin/deepin-terminal/commit/a3e46ed0cc034d3db56f61667f2dcd4c4ad75be3), so when you open a new issue about your bug, don't forget to provide your package version, the DE you are using and the WM you are using, thanks a lot!
